export type Visual = {
  src: string;
  alt: string;
  caption: string;
  kind: "Ảnh chụp thực tế" | "Ảnh từ tài liệu chính thức" | "Sơ đồ minh họa";
  source?: string;
  markers?: { x: number; y: number; label: string }[];
};

export const visuals: Record<string, Visual[]> = {
  "tai-workflow:download": [{ src: "/illustrations/github-download.png", alt: "Trang GitHub crm-lead-workflow với menu Code đang mở và lựa chọn Download ZIP ở cuối menu", caption: "Bấm Code (1), rồi chọn Download ZIP (2). Ảnh chụp kho workflow; vị trí có thể thay đổi theo kích thước màn hình.", kind: "Ảnh chụp thực tế", source: "https://github.com/PhucHuwu/crm-lead-workflow", markers: [{ x: 73, y: 34, label: "1" }, { x: 53, y: 68, label: "2" }] }],
  "tai-workflow:unzip": [{ src: "/illustrations/unzip.svg", alt: "Sơ đồ giải nén trên Windows bằng Extract All và trên Mac bằng bấm đúp ZIP", caption: "Chọn cột đúng hệ điều hành của bạn. Sau giải nén, mở thư mục có inputs và outputs.", kind: "Sơ đồ minh họa" }],
  "tep-thu-muc:open": [{ src: "/illustrations/folder-map.svg", alt: "Sơ đồ thư mục workflow: inputs gồm 01_company_info cho hồ sơ công ty và 02_marketing_materials cho sản phẩm, outputs chứa kết quả", caption: "Đối chiếu tên thư mục trên máy với sơ đồ này. Tài liệu bạn chuẩn bị đặt trong inputs.", kind: "Sơ đồ minh họa" }],
  "tep-thu-muc:put-files": [{ src: "/illustrations/copy-files.svg", alt: "Sơ đồ sao chép ho-so-cong-ty.pdf từ Downloads và dán vào inputs/01_company_info, với phím tắt Windows và Mac", caption: "Hồ sơ công ty dán vào 01_company_info. Tài liệu sản phẩm dùng cùng thao tác, nhưng dán vào 02_marketing_materials.", kind: "Sơ đồ minh họa" }],
  "claude-desktop:code": [{ src: "/illustrations/claude-code-tabs-real.png", alt: "Ảnh Claude Desktop trên Mac, góc trái có biểu tượng Code hình dấu ngoặc và dấu gạch chéo cạnh biểu tượng trò chuyện", caption: "Ảnh chụp thực tế trên Mac. Phiên bản này hiển thị Code bằng biểu tượng </> ở góc trái phía trên (1), thay vì chữ Code. Bấm biểu tượng đó để mở chế độ Code.", kind: "Ảnh chụp thực tế", markers: [{ x: 90, y: 25, label: "1" }] }],
  "claude-desktop:folder": [{ src: "/illustrations/claude-code-no-folder-real.png", alt: "Claude Code Local chưa chọn thư mục: nút No folder nằm phía trên ô nhập yêu cầu", caption: "Trước khi thêm thư mục: kiểm tra Local (1), rồi bấm No folder (2) để mở lựa chọn thư mục workflow. Phiên bản này dùng nhãn No folder thay cho Select folder. Bypass permissions là cấu hình máy chụp; người mới nên chọn Manual.", kind: "Ảnh chụp thực tế", markers: [{ x: 5, y: 15, label: "1" }, { x: 16, y: 15, label: "2" }] }, { src: "/illustrations/claude-code-local-real.png", alt: "Ảnh Claude Code sau khi chọn thư mục crm-lead-workflow", caption: "Sau khi chọn đúng, No folder được thay bằng tên crm-lead-workflow. Đây là trạng thái cần kiểm tra trước khi gửi yêu cầu.", kind: "Ảnh chụp thực tế" }],
  "claude-desktop:open-folder": [{ src: "/illustrations/claude-code-open-folder-real.png", alt: "Menu chọn thư mục mở phía trên nút No folder, có lựa chọn Open folder…", caption: "Sau khi bấm No folder (1), chọn Open folder… (2). Cửa sổ chọn thư mục của máy sẽ mở để bạn chọn bản workflow đã giải nén. Ảnh cắt riêng phần thao tác, không hiển thị các dự án khác.", kind: "Ảnh chụp thực tế", markers: [{ x: 31, y: 72, label: "1" }, { x: 83, y: 27, label: "2" }] }],
  "claude-desktop:add-folder": [{ src: "/illustrations/claude-code-local-real.png", alt: "Ảnh thực tế Claude Code: nút thư mục có dấu cộng nằm ngay sau lựa chọn worktree, phía trên ô nhập yêu cầu", caption: "Bấm nút thư mục có dấu cộng tại vị trí (1). Di chuột lên nút sẽ thấy Add another folder. Sau đó chọn thư mục tài liệu trên máy. Bypass permissions trong ảnh không phải lựa chọn được khuyến nghị cho người mới.", kind: "Ảnh chụp thực tế", markers: [{ x: 50, y: 15, label: "1" }] }],
  "doanh-nghiep:intro": [{ src: "/illustrations/folder-map.svg", alt: "Sơ đồ nơi đặt hồ sơ công ty và tài liệu sản phẩm trong thư mục inputs", caption: "Có tài liệu trên máy? Đặt vào đúng thư mục rồi yêu cầu Claude đọc sau khi đã kết nối.", kind: "Sơ đồ minh họa" }],
  "email:replies": [{ src: "/illustrations/email-flow.svg", alt: "Sơ đồ xử lý phản hồi: trả lời thật dừng chuỗi và tạo task, yêu cầu ngừng thì dừng gửi, chưa trả lời thì tiếp tục kế hoạch", caption: "Dùng sơ đồ để đối chiếu trạng thái trong báo cáo hoặc khi Claude tóm tắt kết quả.", kind: "Sơ đồ minh họa" }],
};
